spring:
  datasource:
    driver-class-name: "net.sf.log4jdbc.sql.jdbcapi.DriverSpy"
    tomcat:
      max-wait: 3000
      max-active: 10
      max-idle: 10
      min-idle: 10
      initial-size: 10
  mvc:
    locale: ko_KR
    date-format: "YYYY-MM-dd"

---
spring:
  profiles: local
  datasource:
    url: "jdbc:log4jdbc:oracle:thin:@172.25.9.32:1570:CDITEST"
    username: "CDI"
    password: "CDI12#$"

---
spring:
  profiles: dev
  datasource:
    url: "jdbc:log4jdbc:oracle:thin:@172.25.9.32:1570:CDITEST"
    username: "CDI"
    password: "CDI12#$"

---
spring:
  profiles: stag
  datasource:
    url: "jdbc:log4jdbc:oracle:thin:@172.25.9.32:1570:CDITEST"
    username: "CDI"
    password: "CDI12#$"

---
# 운영 DB 정보는 다른 GitLab 에서 관리
spring:
  profiles: prod