# COMMON
spring:
  mvc:
    locale: ko_KR
    date-format: "YYYY-MM-dd"
  jackson:
    date-format: "YYYY-MM-dd"
    serialization:
      write_dates_as_timestamps: true
  thymeleaf:
    cache: false
  messages:
    basename: classpath:/messages/message, classpath:/messages/error
    #    always-use-message-format: false # Set whether to always apply the MessageFormat rules, parsing even messages without arguments.
    cache-seconds: -1 # Loaded resource bundle files cache expiration, in seconds. When set to -1, bundles are cached forever.
    encoding: UTF-8 # Message bundles encoding.
    #    fallback-to-system-locale: true # Set whether to fall back to the system Locale if no files for a specific Locale have been found.
  resources:
    static-locations:
      - classpath:/
    add-mappings: true
